<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getEpochTimeinMilli</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoNCiAqIFN5c3RlbS5vdXQucHJpbnRsbiggImN1ckVwb2NoVGltZSAodG9FcG9jaE1pbGxpKSA6
ICIgKw0KICogSW5zdGFudC5ub3coKS50b0Vwb2NoTWlsbGkoKSk7IFZhbHVlc0VtdWxhdG9yLnB1
dChwaXBlbGluZSwgImN1ckVwb2NoVGltZSIsDQogKiBTdHJpbmcudmFsdWVPZihJbnN0YW50Lm5v
dygpLnRvRXBvY2hNaWxsaSgpKSk7DQogKi8NClN0cmluZyByYW5kSW50ID0gU3RyaW5nLnZhbHVl
T2YoVGhyZWFkTG9jYWxSYW5kb20uY3VycmVudCgpLm5leHRJbnQoKSk7DQpTeXN0ZW0ub3V0LnBy
aW50bG4oICJUaHJlYWRMb2NhbFJhbmRvbS5jdXJyZW50KCkubmV4dEludCgpKSA6ICIgKyByYW5k
SW50KTsNClZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgImN1ckVwb2NoVGltZSIsIHJhbmRJ
bnQpOw==</value>
</Values>
